<a href="https://colab.research.google.com/github/Sayak-coder/SIH_26051/blob/main/indoor_temp_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
import numpy as np

In [21]:
df=pd.read_csv('/content/ladakh_indoor_temperature_ml_dataset.csv')
df.head()

,location_id,latitude,longitude,date,month,season,hour,outdoor_temperature_C,wind_speed_mps,thermal_mass_MJ_m3K,insulation_r_value_m2K_W,glazing,GHI_W_m2,best_shelter_material,indoor_temperature_C
0,LAD-001,33.436,77.181,2025-01-01,1,Winter,0,-28.69,3.59,1.859,3.750,0.453,0.0,Super-insulated Rammed Earth (straw/clay cavit...,13.43
1,LAD-001,33.436,77.181,2025-01-01,1,Winter,1,-29.14,3.14,2.360,4.254,0.581,0.0,Super-insulated Rammed Earth (straw/clay cavit...,14.85
2,LAD-001,33.436,77.181,2025-01-01,1,Winter,2,-29.21,2.91,2.365,4.093,0.370,0.0,Super-insulated Rammed Earth (straw/clay cavit...,14.65
3,LAD-001,33.436,77.181,2025-01-01,1,Winter,3,-28.42,2.67,1.907,4.518,0.393,0.0,Super-insulated Rammed Earth (straw/clay cavit...,14.52
4,LAD-001,33.436,77.181,2025-01-01,1,Winter,4,-27.41,2.31,2.603,4.673,0.324,0.0,Super-insulated Rammed Earth (straw/clay cavit...,16.00

In [22]:
df.shape

(8760, 15)

In [24]:
df = df.drop(['location_id', 'date', 'season'], axis=1)
df.head()

,latitude,longitude,month,hour,outdoor_temperature_C,wind_speed_mps,thermal_mass_MJ_m3K,insulation_r_value_m2K_W,glazing,GHI_W_m2,best_shelter_material,indoor_temperature_C
0,33.436,77.181,1,0,-28.69,3.59,1.859,3.750,0.453,0.0,Super-insulated Rammed Earth (straw/clay cavit...,13.43
1,33.436,77.181,1,1,-29.14,3.14,2.360,4.254,0.581,0.0,Super-insulated Rammed Earth (straw/clay cavit...,14.85
2,33.436,77.181,1,2,-29.21,2.91,2.365,4.093,0.370,0.0,Super-insulated Rammed Earth (straw/clay cavit...,14.65
3,33.436,77.181,1,3,-28.42,2.67,1.907,4.518,0.393,0.0,Super-insulated Rammed Earth (straw/clay cavit...,14.52
4,33.436,77.181,1,4,-27.41,2.31,2.603,4.673,0.324,0.0,Super-insulated Rammed Earth (straw/clay cavit...,16.00

In [25]:
df['best_shelter_material'].unique()

array(['Super-insulated Rammed Earth (straw/clay cavity) + unvented Trombe wall & insulated thermal shutter',
       'Stabilized Rammed Earth + Straw-Clay cavity insulation; south Trombe wall with double low-E glazing',
       'Rammed earth thermal mass with adjustable cross-ventilation flaps and external fabric solar shading',
       'Sun-dried adobe bricks with 10cm straw-clay exterior jacket insulation and direct solar-gain south windows',
       'High-thermal-mass adobe walls with deep window overhangs for shading; active night-purge cross ventilation'],
      dtype=object)

In [26]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['best_shelter_material']=le.fit_transform(df['best_shelter_material'])
df['best_shelter_material'].unique()

array([4, 2, 1, 3, 0])

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   latitude                  8760 non-null   float64
 1   longitude                 8760 non-null   float64
 2   month                     8760 non-null   int64
 3   hour                      8760 non-null   int64
 4   outdoor_temperature_C     8760 non-null   float64
 5   wind_speed_mps            8760 non-null   float64
 6   thermal_mass_MJ_m3K       8760 non-null   float64
 7   insulation_r_value_m2K_W  8760 non-null   float64
 8   glazing                   8760 non-null   float64
 9   GHI_W_m2                  8760 non-null   float64
 10  best_shelter_material     8760 non-null   int64
 11  indoor_temperature_C      8760 non-null   float64
dtypes: float64(9), int64(3)
memory usage: 821.4 KB

In [28]:
from sklearn.model_selection import train_test_split
X=df.drop(['indoor_temperature_C'],axis=1)
y=df['indoor_temperature_C']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=45)

In [30]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train['outdoor_temperature_C']=scaler.fit_transform(X_train[['outdoor_temperature_C']])
X_test['outdoor_temperature_C']=scaler.transform(X_test[['outdoor_temperature_C']])

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
lr_model=LinearRegression()
lr_model.fit(X_train,y_train)
y_pred=lr_model.predict(X_test)
print(r2_score(y_test,y_pred))

0.9336343961115078

In [32]:
from xgboost import XGBRegressor
xgb_model=XGBRegressor()
xgb_model.fit(X_train,y_train)
y_pred=xgb_model.predict(X_test)
print(r2_score(y_test,y_pred))

0.9929793120659619